function results = quandtAndrewsVAR(y, p, dates, varargin)
% QUANDTANDREWSVAR
% System-wide Quandt-Andrews sup-Wald structural-break test for a VAR.
%
% The test allows all intercepts and lag coefficients in all equations to
% change at one common, unknown break date.
%
% MODEL
%
%   y_t = c + A_1*y_{t-1} + ... + A_p*y_{t-p} + u_t
%
% NULL HYPOTHESIS
%
%   H0: All VAR coefficients are constant over the complete sample.
%
% ALTERNATIVE HYPOTHESIS
%
%   H1: All or some VAR coefficients change at one unknown common date.
%
% INPUTS
%
%   y       T-by-m matrix containing the VAR variables.
%   p       Number of VAR lags.
%   dates   T-by-1 vector of datetime values or observation numbers.
%
% NAME-VALUE OPTIONS
%
%   'Trim'
%       Fraction trimmed from each end of the effective sample.
%       Default: 0.15
%
%   'MinExtraObservations'
%       Minimum number of observations beyond the number of regressors
%       required in each regime.
%       Default: 5
%
%   'NumSimulations'
%       Number of simulations used to obtain the nonstandard Andrews
%       critical values.
%       Default: 4999
%
%   'Seed'
%       Random-number seed.
%       Default: 4201
%
%   'Plot'
%       Whether to plot the sequence of Wald statistics.
%       Default: true
%
% OUTPUT
%
%   results.SupWald
%   results.PValue
%   results.EstimatedBreakDate
%   results.EstimatedBreakIndex
%   results.WaldPath
%   results.CandidateDates
%   results.CriticalValues
%   results.Summary

%% Parse and validate inputs

if nargin < 3 || isempty(dates)
    dates = (1:size(y, 1))';
end

parser = inputParser;

addParameter( ...
    parser, ...
    'Trim', ...
    0.15, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0 && x < 0.5);

addParameter( ...
    parser, ...
    'MinExtraObservations', ...
    5, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && mod(x, 1) == 0);

addParameter( ...
    parser, ...
    'NumSimulations', ...
    4999, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 99 && mod(x, 1) == 0);

addParameter( ...
    parser, ...
    'Seed', ...
    4201, ...
    @(x) isnumeric(x) && isscalar(x));

addParameter( ...
    parser, ...
    'Plot', ...
    true, ...
    @(x) islogical(x) && isscalar(x));

parse(parser, varargin{:});

trim                   = parser.Results.Trim;
min_extra_observations = parser.Results.MinExtraObservations;
number_of_simulations  = parser.Results.NumSimulations;
seed                   = parser.Results.Seed;
make_plot              = parser.Results.Plot;

validateattributes( ...
    y, ...
    {'numeric'}, ...
    {'2d', 'real', 'finite', 'nonempty'}, ...
    mfilename, ...
    'y');

validateattributes( ...
    p, ...
    {'numeric'}, ...
    {'scalar', 'integer', 'positive'}, ...
    mfilename, ...
    'p');

number_of_original_observations = size(y, 1);
number_of_variables             = size(y, 2);

if number_of_original_observations <= p
    error( ...
        'quandtAndrewsVAR:InsufficientData', ...
        'The number of observations must exceed the number of VAR lags.');
end

dates = dates(:);

if length(dates) ~= number_of_original_observations
    error( ...
        'quandtAndrewsVAR:DateLengthMismatch', ...
        ['The dates vector must contain one entry for every row of the ' ...
         'original VAR data matrix.']);
end

%% Construct the reduced-form VAR regressions

[Y, X] = constructVARData(y, p);

number_of_effective_observations = size(Y, 1);
number_of_regressors             = size(X, 2);

number_of_restrictions = ...
    number_of_regressors * number_of_variables;

effective_dates = dates((p + 1):end);

%% Determine admissible candidate break dates

first_break_from_trimming = ...
    ceil(trim * number_of_effective_observations);

last_break_from_trimming = ...
    floor((1 - trim) * number_of_effective_observations);

minimum_regime_size = ...
    number_of_regressors + min_extra_observations;

first_candidate_break = max( ...
    first_break_from_trimming, ...
    minimum_regime_size);

last_candidate_break = min( ...
    last_break_from_trimming, ...
    number_of_effective_observations - minimum_regime_size);

if first_candidate_break > last_candidate_break
    error( ...
        'quandtAndrewsVAR:NoAdmissibleBreakDates', ...
        ['There are not enough observations to estimate both sides of ' ...
         'the break. The VAR has %d regressors per equation, so each ' ...
         'regime requires at least %d observations.'], ...
        number_of_regressors, ...
        minimum_regime_size);
end

candidate_break_indices = ...
    (first_candidate_break:last_candidate_break)';

candidate_dates = ...
    effective_dates(candidate_break_indices + 1);

%% Calculate the Wald statistic at every candidate break date

wald_path = calculateVARWaldPath( ...
    Y, ...
    X, ...
    candidate_break_indices);

[sup_wald, maximum_location] = max(wald_path);

estimated_break_effective_index = ...
    candidate_break_indices(maximum_location) + 1;

estimated_break_original_index = ...
    p + estimated_break_effective_index;

estimated_break_date = ...
    effective_dates(estimated_break_effective_index);

%% Simulate the nonstandard Quandt-Andrews null distribution

original_random_state = rng;

restore_random_state = onCleanup( ...
    @() rng(original_random_state));

rng(seed);

simulated_sup_wald = simulateAndrewsDistribution( ...
    number_of_effective_observations, ...
    number_of_restrictions, ...
    candidate_break_indices, ...
    number_of_simulations);

p_value = ...
    (1 + sum(simulated_sup_wald >= sup_wald)) / ...
    (number_of_simulations + 1);

critical_probabilities = [0.90; 0.95; 0.99];

critical_values = empiricalQuantile( ...
    simulated_sup_wald, ...
    critical_probabilities);

critical_values_table = table( ...
    [0.10; 0.05; 0.01], ...
    critical_values, ...
    'VariableNames', ...
    {'SignificanceLevel', 'CriticalValue'});

reject_at_five_percent = ...
    sup_wald > critical_values(2);

%% Store results

results = struct();

results.SupWald                      = sup_wald;
results.PValue                       = p_value;
results.RejectAtFivePercent          = reject_at_five_percent;
results.EstimatedBreakDate           = estimated_break_date;
results.EstimatedBreakIndex          = estimated_break_original_index;
results.EstimatedBreakEffectiveIndex = estimated_break_effective_index;

results.WaldPath                  = wald_path;
results.CandidateBreakIndices     = candidate_break_indices;
results.CandidateDates            = candidate_dates;

results.SimulatedSupWald          = simulated_sup_wald;
results.CriticalValues            = critical_values_table;

results.NumberOfVariables         = number_of_variables;
results.NumberOfLags              = p;
results.NumberOfRegressors        = number_of_regressors;
results.NumberOfRestrictions      = number_of_restrictions;
results.EffectiveSampleSize       = number_of_effective_observations;
results.MinimumRegimeSize         = minimum_regime_size;
results.Trim                      = trim;

results.Summary = table( ...
    sup_wald, ...
    p_value, ...
    reject_at_five_percent, ...
    estimated_break_date, ...
    estimated_break_original_index, ...
    number_of_effective_observations, ...
    number_of_regressors, ...
    number_of_restrictions, ...
    'VariableNames', ...
    { ...
    'SupWald', ...
    'PValue', ...
    'RejectAtFivePercent', ...
    'EstimatedBreakDate', ...
    'EstimatedBreakIndex', ...
    'EffectiveSampleSize', ...
    'RegressorsPerEquation', ...
    'NumberOfRestrictions' ...
    });

%% Plot the sequence of test statistics

if make_plot

    fig = figure( ...
        'Position', ...
        [100, 100, 1250, 650]);

    plot( ...
        candidate_dates, ...
        wald_path, ...
        'LineWidth', ...
        1.5, ...
        'DisplayName', ...
        'Candidate-date Wald statistic');

    hold on;

    xline( ...
        estimated_break_date, ...
        '--', ...
        'LineWidth', ...
        1.5, ...
        'DisplayName', ...
        'Estimated breakpoint');

    yline( ...
        critical_values(2), ...
        '--', ...
        'LineWidth', ...
        1.5, ...
        'DisplayName', ...
        '5% critical value');

    title( ...
        'Quandt-Andrews Sup-Wald Test for the Three-Variable VAR', ...
        'FontSize', ...
        18);

    xlabel( ...
        'First observation in the post-break regime', ...
        'FontSize', ...
        16);

    ylabel( ...
        'System-wide Wald statistic', ...
        'FontSize', ...
        16);

    current_axes = gca;
    current_axes.FontSize = 14;

    grid on;
    box on;

    legend( ...
        'Location', ...
        'best', ...
        'FontSize', ...
        14);

    results.Figure = fig;

else

    results.Figure = [];

end

end


%% ------------------------------------------------------------------------
function [Y, X] = constructVARData(y, p)
% Construct the response and regressor matrices for a VAR(p).

[T, number_of_variables] = size(y);

number_of_effective_observations = T - p;

Y = y((p + 1):T, :);

X = ones( ...
    number_of_effective_observations, ...
    1 + p * number_of_variables);

for current_lag = 1:p

    first_column = ...
        2 + (current_lag - 1) * number_of_variables;

    last_column = ...
        1 + current_lag * number_of_variables;

    X(:, first_column:last_column) = ...
        y((p + 1 - current_lag):(T - current_lag), :);

end

end


%% ------------------------------------------------------------------------
function wald_path = calculateVARWaldPath(Y, X, candidate_break_indices)
% Calculate the system-wide Wald statistic for each candidate break.

number_of_observations = size(Y, 1);
number_of_regressors   = size(X, 2);

number_of_candidates = length(candidate_break_indices);

wald_path = NaN(number_of_candidates, 1);

identity_matrix = eye(number_of_regressors);

for candidate_number = 1:number_of_candidates

    break_index = candidate_break_indices(candidate_number);

    X_first  = X(1:break_index, :);
    Y_first  = Y(1:break_index, :);

    X_second = X((break_index + 1):end, :);
    Y_second = Y((break_index + 1):end, :);

    if rank(X_first) < number_of_regressors || ...
            rank(X_second) < number_of_regressors

        error( ...
            'quandtAndrewsVAR:RankDeficiency', ...
            ['The VAR regressor matrix is rank deficient at candidate ' ...
             'break index %d.'], ...
            break_index);

    end

    coefficients_first  = X_first \ Y_first;
    coefficients_second = X_second \ Y_second;

    residuals_first = ...
        Y_first - X_first * coefficients_first;

    residuals_second = ...
        Y_second - X_second * coefficients_second;

    coefficient_difference = ...
        coefficients_first - coefficients_second;

    covariance_denominator = ...
        number_of_observations - 2 * number_of_regressors;

    innovation_covariance = ...
        (residuals_first' * residuals_first + ...
         residuals_second' * residuals_second) / ...
        covariance_denominator;

    innovation_covariance = ...
        (innovation_covariance + innovation_covariance') / 2;

    covariance_of_coefficient_difference = ...
        (X_first' * X_first) \ identity_matrix + ...
        (X_second' * X_second) \ identity_matrix;

    covariance_of_coefficient_difference = ...
        (covariance_of_coefficient_difference + ...
         covariance_of_coefficient_difference') / 2;

    middle_component = ...
        coefficient_difference' * ...
        (covariance_of_coefficient_difference \ ...
         coefficient_difference);

    middle_component = ...
        (middle_component + middle_component') / 2;

    current_wald = trace( ...
        innovation_covariance \ middle_component);

    if current_wald < 0 && current_wald > -1e-8
        current_wald = 0;
    end

    if ~isfinite(current_wald)
        error( ...
            'quandtAndrewsVAR:NonFiniteStatistic', ...
            ['A nonfinite Wald statistic was obtained at candidate ' ...
             'break index %d.'], ...
            break_index);
    end

    wald_path(candidate_number) = real(current_wald);

end

end


%% ------------------------------------------------------------------------
function simulated_sup_wald = simulateAndrewsDistribution( ...
    number_of_observations, ...
    number_of_restrictions, ...
    candidate_break_indices, ...
    number_of_simulations)
% Simulate the supremum of the standardized squared Brownian bridge.

candidate_fractions = ...
    candidate_break_indices / number_of_observations;

normalisation = ...
    candidate_fractions .* (1 - candidate_fractions);

simulated_sup_wald = ...
    zeros(number_of_simulations, 1);

for simulation_number = 1:number_of_simulations

    brownian_increments = randn( ...
        number_of_observations, ...
        number_of_restrictions);

    brownian_motion = ...
        cumsum(brownian_increments, 1) / ...
        sqrt(number_of_observations);

    final_brownian_motion = ...
        brownian_motion(end, :);

    brownian_bridge = ...
        brownian_motion(candidate_break_indices, :) - ...
        candidate_fractions .* final_brownian_motion;

    candidate_statistics = ...
        sum(brownian_bridge .^ 2, 2) ./ normalisation;

    simulated_sup_wald(simulation_number) = ...
        max(candidate_statistics);

end

end


%% ------------------------------------------------------------------------
function quantiles = empiricalQuantile(sample, probabilities)
% Calculate empirical quantiles without requiring a Statistics Toolbox.

sample = sort(sample(:));
probabilities = probabilities(:);

number_of_observations  = length(sample);
number_of_probabilities = length(probabilities);

quantiles = zeros(number_of_probabilities, 1);

for probability_number = 1:number_of_probabilities

    current_probability = probabilities(probability_number);

    interpolation_position = ...
        1 + (number_of_observations - 1) * current_probability;

    lower_position = floor(interpolation_position);
    upper_position = ceil(interpolation_position);

    if lower_position == upper_position

        quantiles(probability_number) = ...
            sample(lower_position);

    else

        interpolation_weight = ...
            interpolation_position - lower_position;

        quantiles(probability_number) = ...
            sample(lower_position) + ...
            interpolation_weight * ...
            (sample(upper_position) - sample(lower_position));

    end

end

end
