%% Four Bayesian Cholesky SVAR specifications with model-specific tags
%
% Model suffixes:
%   _newm      = Romer-Romer new monetary policy measure, no commodity prices
%   _newm_com  = Romer-Romer new monetary policy measure, with commodity prices
%   _ff        = Federal funds rate, no commodity prices
%   _ff_com    = Federal funds rate, with commodity prices
%
% For every model, the code:
%   1. Estimates a Bayesian VAR using bvar_ and its default Jeffreys prior.
%   2. Retains posterior Cholesky IRF draws.
%   3. Normalises every draw separately so the policy variable rises by
%      one percentage point on impact.
%   4. Uses the mean across draws as the plotted point estimate.
%   5. Stores the pointwise standard deviation across draws at every horizon.
%   6. Plots mean +/- one pointwise standard deviation bands.
%
% Because the impact response is included as the first IRF column, setting
% opt.hor = 49 produces horizons 0 through 48 months.

clear;
clc;
close all;

% Fix the random-number seed so the Monte Carlo results are reproducible.
rng(4201);

%% Add the Empirical Macro Toolbox to the MATLAB path

addpath(fullfile(pwd, '..', 'BVAR_', 'bvartools'));

%% Import the Romer and Romer data

data_table = readtable( ...
    "RomerandRomerDataAppendix.xls", ...
    'Sheet', "DATA BY MONTH");

% Display imported variable names.
disp(data_table.Properties.VariableNames);

%% Extract the common data series

% Natural log of industrial production.
industrial_production_log = data_table.LNIPNSA;

% Natural log of producer prices.
producer_price_log = data_table.LNPPINSA;

% Natural log of world commodity prices.
commodity_prices_log = data_table.LNWCP;

% Cumulated Romer and Romer monetary policy shock/new measure.
new_measure = data_table.SUMSHCK;

% Federal funds rate, measured in percentage points.
fed_funds = data_table.FF;

%% Check whether SUMSHCK and SUMSHCKF are identical

same_shock_series = isequal( ...
    data_table.SUMSHCK, ...
    data_table.SUMSHCKF);

fprintf('Are SUMSHCK and SUMSHCKF identical? %d\n', ...
    same_shock_series);

%% Common Bayesian VAR settings

number_of_draws = 500;
irf_horizon_months = 48;

% bvar_ counts the impact response as its first horizon, so 49 columns are
% required to retain horizons 0, 1, ..., 48.
number_of_irf_columns = irf_horizon_months + 1;

desired_policy_impact = 1;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 1. New monetary policy measure VAR without commodity prices: _newm
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Construct the VAR dataset

% Cholesky ordering:
% 1. Log industrial production
% 2. Log producer price level
% 3. Cumulated Romer-Romer new monetary policy measure

y_newm = [
    industrial_production_log, ...
    producer_price_log, ...
    new_measure
    ];

%% Estimate the Bayesian Cholesky SVAR and obtain posterior IRF draws

lags_newm = 36;

opt_newm.hor      = number_of_irf_columns;
opt_newm.K        = number_of_draws;
opt_newm.irf_1STD = 1;
opt_newm.noprint  = 1;

monetary_shock_index_newm = 3;
policy_variable_index_newm = 3;
number_of_variables_newm = 3;

[BVAR_newm, ...
    irfs_draws_newm, ...
    policy_impact_responses_newm, ...
    scaling_factors_newm, ...
    irfs_draws_rescaled_newm, ...
    irfs_mean_newm, ...
    irfs_pointwise_std_newm] = ...
    estimate_bvar_irfs( ...
    y_newm, ...
    lags_newm, ...
    opt_newm, ...
    monetary_shock_index_newm, ...
    policy_variable_index_newm, ...
    number_of_variables_newm, ...
    desired_policy_impact, ...
    '_newm');

number_of_retained_draws_newm = size(irfs_draws_newm, 3);

%% Convert mean IRFs and pointwise standard deviations into plot units

% Industrial production and producer prices are natural logarithms.
log_variable_indices_newm = [1, 2];

[irfs_for_plot_newm, ...
    irfs_pointwise_std_plot_newm, ...
    irfs_lower_newm, ...
    irfs_upper_newm] = ...
    convert_irfs_to_plot_units( ...
    irfs_mean_newm, ...
    irfs_pointwise_std_newm, ...
    log_variable_indices_newm);

%% Store the pointwise standard deviations in a labelled table

horizons_newm = 0:(size(irfs_for_plot_newm, 2) - 1);
number_of_horizons_newm = numel(horizons_newm);

pointwise_std_table_newm = array2table( ...
    [horizons_newm', irfs_pointwise_std_plot_newm'], ...
    'VariableNames', { ...
    'Horizon', ...
    'Output', ...
    'PriceLevel', ...
    'CumulatedNewMeasure' ...
    });

%% Display normalisation information

fprintf('\n_newm posterior IRF draws retained: %d\n', ...
    number_of_retained_draws_newm);

fprintf('_newm mean original policy impact response: %.6f\n', ...
    mean(policy_impact_responses_newm, 'omitnan'));

fprintf('_newm mean draw-specific scaling factor: %.6f\n', ...
    mean(scaling_factors_newm, 'omitnan'));

fprintf(['_newm mean rescaled policy impact response ', ...
    '(should equal 1): %.6f\n'], ...
    irfs_for_plot_newm(policy_variable_index_newm, 1));

fprintf(['_newm pointwise standard deviation of the policy response ', ...
    'on impact (should be approximately zero): %.6e\n'], ...
    irfs_pointwise_std_plot_newm(policy_variable_index_newm, 1));

%% Plot the _newm impulse responses

panel_indices_newm = [3, 1, 2];

panel_titles_newm = {
    'Effect on the Cumulated Shock'
    'Effect on Output'
    'Effect on the Price Level'
    };

y_axis_labels_newm = {
    'Percentage Points'
    'Percent'
    'Percent'
    };

y_axis_limits_newm = {
    [0, 1.2]
    [-5, 2]
    [-7, 1]
    };

y_axis_ticks_newm = {
    0:0.2:1.2
    -5:1:2
    -7:1:1
    };

figure_title_newm = ...
    'Romer-Romer Monetary Policy Shock VAR';

[figure_newm, plot_layout_newm, axes_newm] = ...
    plot_tagged_irfs_with_bands( ...
    irfs_for_plot_newm, ...
    irfs_lower_newm, ...
    irfs_upper_newm, ...
    horizons_newm, ...
    panel_indices_newm, ...
    panel_titles_newm, ...
    y_axis_labels_newm, ...
    y_axis_limits_newm, ...
    y_axis_ticks_newm, ...
    [100, 50, 750, 1050], ...
    figure_title_newm);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 2. New monetary policy measure VAR with commodity prices: _newm_com
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Construct the VAR dataset

% Cholesky ordering:
% 1. Log industrial production
% 2. Log producer price level
% 3. Log world commodity prices
% 4. Cumulated Romer-Romer new monetary policy measure

y_newm_com = [
    industrial_production_log, ...
    producer_price_log, ...
    commodity_prices_log, ...
    new_measure
    ];

%% Estimate the Bayesian Cholesky SVAR and obtain posterior IRF draws

lags_newm_com = 36;

opt_newm_com.hor      = number_of_irf_columns;
opt_newm_com.K        = number_of_draws;
opt_newm_com.irf_1STD = 1;
opt_newm_com.noprint  = 1;

monetary_shock_index_newm_com = 4;
policy_variable_index_newm_com = 4;
number_of_variables_newm_com = 4;

[BVAR_newm_com, ...
    irfs_draws_newm_com, ...
    policy_impact_responses_newm_com, ...
    scaling_factors_newm_com, ...
    irfs_draws_rescaled_newm_com, ...
    irfs_mean_newm_com, ...
    irfs_pointwise_std_newm_com] = ...
    estimate_bvar_irfs( ...
    y_newm_com, ...
    lags_newm_com, ...
    opt_newm_com, ...
    monetary_shock_index_newm_com, ...
    policy_variable_index_newm_com, ...
    number_of_variables_newm_com, ...
    desired_policy_impact, ...
    '_newm_com');

number_of_retained_draws_newm_com = size(irfs_draws_newm_com, 3);

%% Convert mean IRFs and pointwise standard deviations into plot units

% Industrial production, producer prices and commodity prices are logs.
log_variable_indices_newm_com = [1, 2, 3];

[irfs_for_plot_newm_com, ...
    irfs_pointwise_std_plot_newm_com, ...
    irfs_lower_newm_com, ...
    irfs_upper_newm_com] = ...
    convert_irfs_to_plot_units( ...
    irfs_mean_newm_com, ...
    irfs_pointwise_std_newm_com, ...
    log_variable_indices_newm_com);

%% Store the pointwise standard deviations in a labelled table

horizons_newm_com = 0:(size(irfs_for_plot_newm_com, 2) - 1);
number_of_horizons_newm_com = numel(horizons_newm_com);

pointwise_std_table_newm_com = array2table( ...
    [horizons_newm_com', irfs_pointwise_std_plot_newm_com'], ...
    'VariableNames', { ...
    'Horizon', ...
    'Output', ...
    'PriceLevel', ...
    'CommodityPrices', ...
    'CumulatedNewMeasure' ...
    });

%% Display normalisation information

fprintf('\n_newm_com posterior IRF draws retained: %d\n', ...
    number_of_retained_draws_newm_com);

fprintf('_newm_com mean original policy impact response: %.6f\n', ...
    mean(policy_impact_responses_newm_com, 'omitnan'));

fprintf('_newm_com mean draw-specific scaling factor: %.6f\n', ...
    mean(scaling_factors_newm_com, 'omitnan'));

fprintf(['_newm_com mean rescaled policy impact response ', ...
    '(should equal 1): %.6f\n'], ...
    irfs_for_plot_newm_com(policy_variable_index_newm_com, 1));

fprintf(['_newm_com pointwise standard deviation of the policy response ', ...
    'on impact (should be approximately zero): %.6e\n'], ...
    irfs_pointwise_std_plot_newm_com(policy_variable_index_newm_com, 1));

%% Plot the _newm_com impulse responses

% Commodity prices remain in the estimated VAR but their IRF is not plotted.
panel_indices_newm_com = [4, 1, 2];

panel_titles_newm_com = {
    'Effect on the Cumulated Shock'
    'Effect on Output'
    'Effect on the Price Level'
    };

y_axis_labels_newm_com = {
    'Percentage Points'
    'Percent'
    'Percent'
    };

y_axis_limits_newm_com = {
    [0, 1.2]
    [-5, 2]
    [-7, 1]
    };

y_axis_ticks_newm_com = {
    0:0.2:1.2
    -5:1:2
    -7:1:1
    };

figure_title_newm_com = ...
    'Romer-Romer Monetary Policy Shock VAR with Commodity Prices';

[figure_newm_com, plot_layout_newm_com, axes_newm_com] = ...
    plot_tagged_irfs_with_bands( ...
    irfs_for_plot_newm_com, ...
    irfs_lower_newm_com, ...
    irfs_upper_newm_com, ...
    horizons_newm_com, ...
    panel_indices_newm_com, ...
    panel_titles_newm_com, ...
    y_axis_labels_newm_com, ...
    y_axis_limits_newm_com, ...
    y_axis_ticks_newm_com, ...
    [900, 50, 800, 1050], ...
    figure_title_newm_com);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 3. Federal funds rate VAR without commodity prices: _ff
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Construct the VAR dataset

% Cholesky ordering:
% 1. Log industrial production
% 2. Log producer price level
% 3. Federal funds rate

y_ff = [
    industrial_production_log, ...
    producer_price_log, ...
    fed_funds
    ];

%% Estimate the Bayesian Cholesky SVAR and obtain posterior IRF draws

lags_ff = 36;

opt_ff.hor      = number_of_irf_columns;
opt_ff.K        = number_of_draws;
opt_ff.irf_1STD = 1;
opt_ff.noprint  = 1;

monetary_shock_index_ff = 3;
policy_variable_index_ff = 3;
number_of_variables_ff = 3;

[BVAR_ff, ...
    irfs_draws_ff, ...
    policy_impact_responses_ff, ...
    scaling_factors_ff, ...
    irfs_draws_rescaled_ff, ...
    irfs_mean_ff, ...
    irfs_pointwise_std_ff] = ...
    estimate_bvar_irfs( ...
    y_ff, ...
    lags_ff, ...
    opt_ff, ...
    monetary_shock_index_ff, ...
    policy_variable_index_ff, ...
    number_of_variables_ff, ...
    desired_policy_impact, ...
    '_ff');

number_of_retained_draws_ff = size(irfs_draws_ff, 3);

%% Convert mean IRFs and pointwise standard deviations into plot units

% Industrial production and producer prices are natural logarithms.
log_variable_indices_ff = [1, 2];

[irfs_for_plot_ff, ...
    irfs_pointwise_std_plot_ff, ...
    irfs_lower_ff, ...
    irfs_upper_ff] = ...
    convert_irfs_to_plot_units( ...
    irfs_mean_ff, ...
    irfs_pointwise_std_ff, ...
    log_variable_indices_ff);

%% Store the pointwise standard deviations in a labelled table

horizons_ff = 0:(size(irfs_for_plot_ff, 2) - 1);
number_of_horizons_ff = numel(horizons_ff);

pointwise_std_table_ff = array2table( ...
    [horizons_ff', irfs_pointwise_std_plot_ff'], ...
    'VariableNames', { ...
    'Horizon', ...
    'Output', ...
    'PriceLevel', ...
    'FederalFundsRate' ...
    });

%% Display normalisation information

fprintf('\n_ff posterior IRF draws retained: %d\n', ...
    number_of_retained_draws_ff);

fprintf('_ff mean original policy impact response: %.6f\n', ...
    mean(policy_impact_responses_ff, 'omitnan'));

fprintf('_ff mean draw-specific scaling factor: %.6f\n', ...
    mean(scaling_factors_ff, 'omitnan'));

fprintf(['_ff mean rescaled policy impact response ', ...
    '(should equal 1): %.6f\n'], ...
    irfs_for_plot_ff(policy_variable_index_ff, 1));

fprintf(['_ff pointwise standard deviation of the policy response ', ...
    'on impact (should be approximately zero): %.6e\n'], ...
    irfs_pointwise_std_plot_ff(policy_variable_index_ff, 1));

%% Plot the _ff impulse responses

panel_indices_ff = [3, 1, 2];

panel_titles_ff = {
    'Effect on the Federal Funds Rate'
    'Effect on Output'
    'Effect on the Price Level'
    };

y_axis_labels_ff = {
    'Percentage Points'
    'Percent'
    'Percent'
    };

y_axis_limits_ff = {
    [0, 1.2]
    [-5, 2]
    [-7, 1]
    };

y_axis_ticks_ff = {
    0:0.2:1.2
    -5:1:2
    -7:1:1
    };

figure_title_ff = ...
    'Federal Funds Rate VAR';

[figure_ff, plot_layout_ff, axes_ff] = ...
    plot_tagged_irfs_with_bands( ...
    irfs_for_plot_ff, ...
    irfs_lower_ff, ...
    irfs_upper_ff, ...
    horizons_ff, ...
    panel_indices_ff, ...
    panel_titles_ff, ...
    y_axis_labels_ff, ...
    y_axis_limits_ff, ...
    y_axis_ticks_ff, ...
    [100, 100, 750, 1050], ...
    figure_title_ff);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% 4. Federal funds rate VAR with commodity prices: _ff_com
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Construct the VAR dataset

% Cholesky ordering:
% 1. Log industrial production
% 2. Log producer price level
% 3. Log world commodity prices
% 4. Federal funds rate

y_ff_com = [
    industrial_production_log, ...
    producer_price_log, ...
    commodity_prices_log, ...
    fed_funds
    ];

%% Estimate the Bayesian Cholesky SVAR and obtain posterior IRF draws

lags_ff_com = 36;

opt_ff_com.hor      = number_of_irf_columns;
opt_ff_com.K        = number_of_draws;
opt_ff_com.irf_1STD = 1;
opt_ff_com.noprint  = 1;

monetary_shock_index_ff_com = 4;
policy_variable_index_ff_com = 4;
number_of_variables_ff_com = 4;

[BVAR_ff_com, ...
    irfs_draws_ff_com, ...
    policy_impact_responses_ff_com, ...
    scaling_factors_ff_com, ...
    irfs_draws_rescaled_ff_com, ...
    irfs_mean_ff_com, ...
    irfs_pointwise_std_ff_com] = ...
    estimate_bvar_irfs( ...
    y_ff_com, ...
    lags_ff_com, ...
    opt_ff_com, ...
    monetary_shock_index_ff_com, ...
    policy_variable_index_ff_com, ...
    number_of_variables_ff_com, ...
    desired_policy_impact, ...
    '_ff_com');

number_of_retained_draws_ff_com = size(irfs_draws_ff_com, 3);

%% Convert mean IRFs and pointwise standard deviations into plot units

% Industrial production, producer prices and commodity prices are logs.
log_variable_indices_ff_com = [1, 2, 3];

[irfs_for_plot_ff_com, ...
    irfs_pointwise_std_plot_ff_com, ...
    irfs_lower_ff_com, ...
    irfs_upper_ff_com] = ...
    convert_irfs_to_plot_units( ...
    irfs_mean_ff_com, ...
    irfs_pointwise_std_ff_com, ...
    log_variable_indices_ff_com);

%% Store the pointwise standard deviations in a labelled table

horizons_ff_com = 0:(size(irfs_for_plot_ff_com, 2) - 1);
number_of_horizons_ff_com = numel(horizons_ff_com);

pointwise_std_table_ff_com = array2table( ...
    [horizons_ff_com', irfs_pointwise_std_plot_ff_com'], ...
    'VariableNames', { ...
    'Horizon', ...
    'Output', ...
    'PriceLevel', ...
    'CommodityPrices', ...
    'FederalFundsRate' ...
    });

%% Display normalisation information

fprintf('\n_ff_com posterior IRF draws retained: %d\n', ...
    number_of_retained_draws_ff_com);

fprintf('_ff_com mean original policy impact response: %.6f\n', ...
    mean(policy_impact_responses_ff_com, 'omitnan'));

fprintf('_ff_com mean draw-specific scaling factor: %.6f\n', ...
    mean(scaling_factors_ff_com, 'omitnan'));

fprintf(['_ff_com mean rescaled policy impact response ', ...
    '(should equal 1): %.6f\n'], ...
    irfs_for_plot_ff_com(policy_variable_index_ff_com, 1));

fprintf(['_ff_com pointwise standard deviation of the policy response ', ...
    'on impact (should be approximately zero): %.6e\n'], ...
    irfs_pointwise_std_plot_ff_com(policy_variable_index_ff_com, 1));

%% Plot the _ff_com impulse responses

% Commodity prices remain in the estimated VAR but their IRF is not plotted.
panel_indices_ff_com = [4, 1, 2];

panel_titles_ff_com = {
    'Effect on the Federal Funds Rate'
    'Effect on Output'
    'Effect on the Price Level'
    };

y_axis_labels_ff_com = {
    'Percentage Points'
    'Percent'
    'Percent'
    };

y_axis_limits_ff_com = {
    [0, 1.2]
    [-5, 2]
    [-7, 1]
    };

y_axis_ticks_ff_com = {
    0:0.2:1.2
    -5:1:2
    -7:1:1
    };

figure_title_ff_com = ...
    'Federal Funds Rate VAR with Commodity Prices';

[figure_ff_com, plot_layout_ff_com, axes_ff_com] = ...
    plot_tagged_irfs_with_bands( ...
    irfs_for_plot_ff_com, ...
    irfs_lower_ff_com, ...
    irfs_upper_ff_com, ...
    horizons_ff_com, ...
    panel_indices_ff_com, ...
    panel_titles_ff_com, ...
    y_axis_labels_ff_com, ...
    y_axis_limits_ff_com, ...
    y_axis_ticks_ff_com, ...
    [900, 100, 800, 1050], ...
    figure_title_ff_com);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Local estimation and plotting functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [BVAR_model, ...
        irfs_draws, ...
        policy_impact_responses, ...
        scaling_factors, ...
        irfs_draws_rescaled, ...
        irfs_mean, ...
        irfs_pointwise_std] = ...
        estimate_bvar_irfs( ...
        y, ...
        lags, ...
        options, ...
        monetary_shock_index, ...
        policy_variable_index, ...
        number_of_variables, ...
        desired_policy_impact, ...
        model_tag)
%ESTIMATE_BVAR_IRFS Estimate a BVAR and summarise posterior Cholesky IRFs.
%
% Output dimensions:
%   irfs_draws              variable x horizon x draw
%   irfs_draws_rescaled     variable x horizon x draw
%   irfs_mean               variable x horizon
%   irfs_pointwise_std      variable x horizon
%
% Each posterior draw is separately normalised so the policy variable has
% the same desired impact response in every draw. The mean and pointwise
% standard deviation are then computed across these normalised draws.

    BVAR_model = bvar_(y, lags, options);

    if ~isfield(BVAR_model, 'ir_draws')
        error(['The bvar_ output for ', model_tag, ...
            ' does not contain the field ir_draws.']);
    end

    irfs_draws = squeeze( ...
        BVAR_model.ir_draws(:, :, monetary_shock_index, :) ...
        );

    % With K > 1, the expected dimensions after squeeze are:
    % variable x horizon x draw.
    if ndims(irfs_draws) ~= 3
        error(['The extracted posterior IRFs for ', model_tag, ...
            ' are not a three-dimensional variable-by-horizon-by-draw ', ...
            'array. Check BVAR_model.ir_draws and options.K.']);
    end

    if size(irfs_draws, 1) ~= number_of_variables
        error(['The extracted posterior IRFs for ', model_tag, ...
            ' do not have the expected number of variables in their rows.']);
    end

    policy_impact_responses = squeeze( ...
        irfs_draws(policy_variable_index, 1, :) ...
        );

    policy_impact_responses = policy_impact_responses(:);

    invalid_policy_impacts = ...
        ~isfinite(policy_impact_responses) | ...
        abs(policy_impact_responses) < 1e-12;

    if any(invalid_policy_impacts)
        error(['At least one posterior IRF draw for ', model_tag, ...
            ' has an invalid or approximately zero policy impact response, ', ...
            'so draw-specific normalisation cannot be performed.']);
    end

    scaling_factors = ...
        desired_policy_impact ./ policy_impact_responses;

    irfs_draws_rescaled = ...
        irfs_draws .* reshape(scaling_factors, 1, 1, []);

    % The plotted point estimate is the mean across posterior IRF draws.
    irfs_mean = mean( ...
        irfs_draws_rescaled, ...
        3, ...
        'omitnan');

    % This matrix stores the pointwise standard deviation for every
    % variable and every horizon.
    irfs_pointwise_std = std( ...
        irfs_draws_rescaled, ...
        0, ...
        3, ...
        'omitnan');
end


function [irfs_mean_plot, ...
        irfs_pointwise_std_plot, ...
        irfs_lower_plot, ...
        irfs_upper_plot] = ...
        convert_irfs_to_plot_units( ...
        irfs_mean, ...
        irfs_pointwise_std, ...
        log_variable_indices)
%CONVERT_IRFS_TO_PLOT_UNITS Convert log responses to percentage responses.
%
% The mean and standard deviation are transformed using the same linear
% scaling. The pointwise bands are mean +/- one standard deviation.

    irfs_mean_plot = irfs_mean;
    irfs_pointwise_std_plot = irfs_pointwise_std;

    irfs_mean_plot(log_variable_indices, :) = ...
        100 .* irfs_mean(log_variable_indices, :);

    irfs_pointwise_std_plot(log_variable_indices, :) = ...
        100 .* irfs_pointwise_std(log_variable_indices, :);

    irfs_lower_plot = ...
        irfs_mean_plot - irfs_pointwise_std_plot;

    irfs_upper_plot = ...
        irfs_mean_plot + irfs_pointwise_std_plot;
end


function [figure_handle, layout_handle, axes_handles] = ...
        plot_tagged_irfs_with_bands( ...
        irfs_mean_plot, ...
        irfs_lower_plot, ...
        irfs_upper_plot, ...
        horizons, ...
        panel_indices, ...
        panel_titles, ...
        y_axis_labels, ...
        y_axis_limits, ...
        y_axis_ticks, ...
        figure_position, ...
        figure_title)
%PLOT_TAGGED_IRFS_WITH_BANDS Plot mean IRFs and one-standard-deviation bands.
%
% The solid line is the posterior mean IRF. The dashed lines are the
% pointwise posterior mean plus and minus one standard deviation.

    number_of_panels = numel(panel_indices);
    panel_letters = 'abcdefghijklmnopqrstuvwxyz';

    figure_handle = figure( ...
        'Position', figure_position, ...
        'Color', 'w');

    layout_handle = tiledlayout(number_of_panels, 1);
    layout_handle.TileSpacing = 'compact';
    layout_handle.Padding = 'compact';

    title( ...
        layout_handle, ...
        figure_title, ...
        'FontSize', 20, ...
        'FontWeight', 'bold');

    axes_handles = gobjects(number_of_panels, 1);

    for panel = 1:number_of_panels

        axes_handles(panel) = nexttile(layout_handle);
        current_axis = axes_handles(panel);
        current_variable = panel_indices(panel);

        % Lower one-standard-deviation band.
        plot( ...
            current_axis, ...
            horizons, ...
            irfs_lower_plot(current_variable, :), ...
            'k--', ...
            'LineWidth', 1.2);

        hold(current_axis, 'on');

        % Upper one-standard-deviation band.
        plot( ...
            current_axis, ...
            horizons, ...
            irfs_upper_plot(current_variable, :), ...
            'k--', ...
            'LineWidth', 1.2);

        % Posterior mean impulse response.
        plot( ...
            current_axis, ...
            horizons, ...
            irfs_mean_plot(current_variable, :), ...
            'k-', ...
            'LineWidth', 1.8);

        yline( ...
            current_axis, ...
            0, ...
            'k:', ...
            'LineWidth', 1);

        title( ...
            current_axis, ...
            sprintf('%s. %s', ...
            panel_letters(panel), ...
            panel_titles{panel}), ...
            'FontSize', 18);

        xlabel( ...
            current_axis, ...
            'Months after Shock', ...
            'FontSize', 16);

        ylabel( ...
            current_axis, ...
            y_axis_labels{panel}, ...
            'FontSize', 16);

        if ~isempty(y_axis_limits{panel})
            ylim(current_axis, y_axis_limits{panel});
        end

        if ~isempty(y_axis_ticks{panel})
            yticks(current_axis, y_axis_ticks{panel});
        end

        xlim(current_axis, [0, 48]);
        xticks(current_axis, 0:3:48);

        current_axis.FontSize = 14;
        current_axis.Box = 'on';
        current_axis.LineWidth = 1;
    end

    linkaxes(axes_handles, 'x');
end
